/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.51
 * Generated at: 2020-03-06 17:57:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class contactUs_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"css/style.css\" >\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.4.1.slim.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js\"></script>\r\n");
      out.write("    <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Quattrocento+Sans&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header_Contact.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t<div class=\"main-content\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-xs-12 col-sm-9 col-lg-9\">\r\n");
      out.write("                        <div class=\"header-content\">\r\n");
      out.write("                            <p style=\"margin-top: 20px; font-size:25px; font-weight: bold;\">Find us</p>     \r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"content\">\r\n");
      out.write("                            <div class=\"page1\">\r\n");
      out.write("                                <div class=\"row\">\r\n");
      out.write("                                    <div class=\"col-xs-12 col-sm-6 col-lg-6\">\r\n");
      out.write("                                        <div class=\"header-content\" style=\"margin-left: -20px;\">\r\n");
      out.write("                                            <p style=\"font-size:20px; font-weight: bold;\">Address and contact: <p>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div>\r\n");
      out.write("                                            <div class=\"country\" >\r\n");
      out.write("                                                <p>The Sushi Restaurant<br>New York, NY, USA</p>\r\n");
      out.write("                                           </div>\r\n");
      out.write("                   \r\n");
      out.write("                                           <div class=\"row\">\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-3\">\r\n");
      out.write("      \t\t\t\t\t\t\t\t\t\t\t\tTel\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-9\">\r\n");
      out.write("      \t\t\t\t\t\t\t\t\t\t\t\t <a href=\"tel:12345\" class=\"info\">\r\n");
      out.write("                                        \t\t\t\t12345\r\n");
      out.write("                                   \t\t\t\t\t </a>\t\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-3\">\r\n");
      out.write("      \t\t\t\t\t\t\t\t\t\t\t\tEmail:  \r\n");
      out.write("    \t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-9\">\r\n");
      out.write("      \t\t\t\t\t\t\t\t\t\t\t\t<a href=\"mailto:your-email@your-email.com\" class=\"info\">\r\n");
      out.write("                                                       \tyour-email@your-email.com\r\n");
      out.write("                                                    </a>\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-xs-12 col-sm-6 col-lg-6\" >\r\n");
      out.write("                                        <div class=\"header-content\" style=\"margin-left: -20px;\">\r\n");
      out.write("                                            <p style=\"font-size:20px; font-weight: bold;\">Opening hour: </p>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div>\r\n");
      out.write("                                            <p style=\"line-height: normal;\">\r\n");
      out.write("                                                Monday Closed<br>\r\n");
      out.write("                                                Tuesday 12 - 22<br>\r\n");
      out.write("                                                Wednesday 12 - 22<br>\r\n");
      out.write("                                                Thursday 12 - 22<br>\r\n");
      out.write("                                                Friday 11 - 23<br>\r\n");
      out.write("                                                Saturday 11 - 23<br>\r\n");
      out.write("                                                Sunday 11 - 22\r\n");
      out.write("                                            </p>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"map\">\r\n");
      out.write("                                <div id=\"map-container-google-1\" class=\"z-depth-1-half map-container\" style=\"height: 500px; border-radius: 10px\">\r\n");
      out.write("                                    <iframe src=\"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3834.2803951558517!2d108.2034673148582!3d16.050932988892235!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x314219bbac29a89b%3A0xd1216d40b4bca153!2zMTUwIER1eSBUw6JuLCBIw7JhIFRodeG6rW4gTmFtLCBI4bqjaSBDaMOidSwgxJDDoCBO4bq1bmcgNTUwMDAw!5e0!3m2!1svi!2s!4v1582770866774!5m2!1svi!2s\"\r\n");
      out.write("                                      style=\"border:0\"></iframe>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      \r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-xs-0 col-sm-3 col-lg-3\">\r\n");
      out.write("                        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "share.jsp", out, false);
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"footer\">\r\n");
      out.write("                ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "counter.jsp", out, false);
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
